# Generated by Django 2.1.2 on 2018-10-21 06:52

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unravel', '0003_documenttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('archived_date', models.DateTimeField(blank=True, null=True)),
                ('last_authored_date', models.DateTimeField(blank=True, help_text='Date this version of the document was most recently edited.', null=True)),
                ('content_language', models.CharField(choices=[('english', 'English Language'), ('danish', 'Danish Language'), ('dutch', 'Dutch Language'), ('finnish', 'Finnish Language'), ('french', 'French Language'), ('german', 'German Language'), ('hungarian', 'Hungarian Language'), ('italian', 'Italian Language'), ('norwegian', 'Norwegian Language'), ('portuguese', 'Portuguese Language'), ('romanian', 'Romanian Language'), ('russian', 'Russian Language'), ('spanish', 'Spanish Language'), ('swedish', 'Swedish Language'), ('turkish', 'Turkish Language'), ('simple', 'Unspecified Language')], default='english', help_text='The language of the document text.', max_length=20)),
                ('content_file', models.FileField(blank=True, help_text='The file containing the document content.', max_length=200, null=True, upload_to='document/%Y/%m/%d/')),
                ('content_text_raw', models.TextField(blank=True, help_text='The raw document text.', null=True)),
                ('content_text_formatted', models.TextField(blank=True, help_text='The formatted document text.', null=True)),
                ('content_text_norm', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, help_text='The document text normalised using the specified language.', null=True)),
                ('content_text_simple', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, help_text='The document text normalised using a simpler method.', null=True)),
                ('archived_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unravel_documentversion_archived', related_query_name='unravel_documentversion_archivers', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unravel_documentversion_created', related_query_name='unravel_documentversion_creators', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Metadata for the document that does not change between versions.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='unravel.Document')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unravel_documentversion_updated', related_query_name='unravel_documentversion_updaters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
            },
        ),
    ]
